name: dartssh2
version: 2.9.1-pre
description: SSH and SFTP client written in pure Dart, aiming to be feature-rich as well as easy to use.
homepage: https://github.com/TerminalStudio/dartssh2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  asn1lib: ^1.5.3
  convert: ^3.1.1
  meta: ^1.15.0
  pointycastle: ^3.9.1
  pinenacl: ^0.6.0

dev_dependencies:
  build_runner: ^2.1.1
  dart_code_metrics: ^4.16.0
  lints: ^2.0.0
  test: ^1.6.5

false_secrets:
  - test
