name: Dart

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # sdk: [stable, beta, dev, 2.10.3, 2.12.0-29.10.beta]
        sdk: [stable, dev]

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Activate coverage tool
        run: dart pub global activate coverage

      - name: Run tests
        run: dart pub global run coverage:test_with_coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v4
